### ISSUE TITLE
handlerFactory calls res.send() breaking controllers wanting to stream to the response body

### ISSUE THREAD

**Issue by Place1** [inversify/inversify-express-utils#155]
i've got this endpoint:

```typescript
  @httpGet('/')
  async getTheThing(@response() res: Response) {
    try {
      const fileStream = await this.storage.getTheThing();
      res.setHeader('content-type', 'application/tar');
      fileStream.pipe(res);
    } catch (error) {
      return res.status(404).send(error);
    }
```

This fails with:

```
Error: write after end
    at write_ (_http_outgoing.js:631:15)
    at ServerResponse.write (_http_outgoing.js:626:10)
    at IncomingMessage.ondata (_stream_readable.js:646:20)
    at IncomingMessage.emit (events.js:160:13)
    at IncomingMessage.Readable.read (_stream_readable.js:482:10)
    at flow (_stream_readable.js:853:34)
    at resume_ (_stream_readable.js:835:3)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

Because the [handlerFactory at this line](https://github.com/inversify/inversify-express-utils/blob/fd0c826e22c980edfea2f017b5b322885a3d5351/src/server.ts#L233) calls `res.send()` which closes the request while the stream is still being written.

I think if a controller uses `@response()` to get access to the response object then the handler factory shouldn't touch the response object at all.

**Comment by Place1** [comment]
Here's a workaround incase others find this post:
```typescript
  @httpGet('/')
  async getTheThing(@response() res: Response) {
    try {
      const fileStream = await this.storage.getTheThing();
      res.setHeader('content-type', 'application/tar');
      fileStream.pipe(res);

      # we want to wait for the stream to be consumed so that
      # that when inversify-express-utils calls `res.send()` it doesn't
      # crash a still-in-progress stream pipe.
      await streamFinished(fileStream);
    } catch (error) {
      return res.status(404).send(error);
    }
```
```
function streamFinished(stream: NodeJS.ReadableStream) {
  return new Promise((resolve, reject) => {
    stream.on('end', () => resolve());
    stream.on('error', () => reject());
  });
}
```

**Comment by remojansen** [comment]
Moved the issue to the main repo https://github.com/inversify/InversifyJS/issues/850
